---
allmon3_enabled: false
allmon3_username: node-factory
allmon3_ami_host: 127.0.0.1
allmon3_ami_port: 5038
allmon3_ami_user: node-factory
allmon3_http_bind_addr: 127.0.0.1
allmon3_http_port: 16080
allmon3_ws_bind_addr: 127.0.0.1
allmon3_ws_port_start: 16700
